name: Build, Test and Deploy to Test

on:
  push:
    branches:
      - do_test
    paths:
      - 'config/**'
      - src
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: dbc-bot
          token: ${{ env.DO_TOKEN }}
          images: '[{
            "name": "dbc-bot",
            "repository": "registry.digitalocean.com/production/bc-bot",
            "tag": "${{steps.github-sha.outputs.sha}}"
            }]'
