name: Build, Test and Deploy to Test

on:
  push:
    branches:
      - test2

env:
  BRAWL_STARS_TOKEN: ${{ secrets.BRAWL_STARS_TOKEN }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: SSH into the server and pull the image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
          password: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
          script: |
            docker-compose -f /path/to/docker-compose.yml pull
            docker-compose -f /path/to/docker-compose.yml up -d